---
- name: Apply security updates only
  hosts: all
  become: yes

  tasks:
    - name: Upgrade only security packages
      apt:
        upgrade: dist
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
